const MONITOR_STATUS = {
  DOWN: 0,
  UP: 1,
  ALERTING: 2
};

const CHECKLIST_STATUS = {
  PENDING: 'pending',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  NA: 'na'
};

const ALLOWED_STATUSES = [
  CHECKLIST_STATUS.PENDING,
  CHECKLIST_STATUS.IN_PROGRESS,
  CHECKLIST_STATUS.COMPLETED,
  CHECKLIST_STATUS.NA
];

module.exports = { MONITOR_STATUS, CHECKLIST_STATUS, ALLOWED_STATUSES };
